#!/usr/bin/sh

#!/usr/bin/sh

build() {
  echo "Building arb-util"
  cargo b --bin arb-util --all-features -r
}
install() {
  echo "Installing rrr"

  sudo rm /usr/bin/arb-util || echo "arb-util was not installed, I see..."
  sudo cp target/release/arb-util /usr/bin/arb-util
}

build && install
